# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Antoine Rolet's homepage
email:
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "arolet.github.io" # the base hostname & protocol for your site
github_username: arolet
linkedin_username: antoine-rolet-3aba0a257
linkedin_displayname: antoine-rolet

# Build settings
markdown: kramdown
